import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://devkeydemands.underdev.in/login');
  await page.getByPlaceholder('Enter your email ID').click();
  await page.getByPlaceholder('Enter your email ID').fill('devkeydemand@gmail.com');
  await page.getByPlaceholder('Enter your password').click();
  await page.getByPlaceholder('Enter your password').click();
  await page.getByPlaceholder('Enter your password').fill('superadmin@1234');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('div').filter({ hasText: '× Login successful.OKNoCancel' }).first().click();
  await page.getByRole('link', { name: 'Customers Customers' }).click();
  await page.getByRole('cell', { name: '22', exact: true }).click();
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowRight');
  await page.getByRole('row', { name: '1 April testing New test April Karnataka - All cities,..(View all) 22 janani 05-04-2023, 02:30 PM' }).locator('svg').first().click();
  await page.getByRole('button', { name: 'Add Demand' }).click();
  await page.getByRole('combobox').selectOption('63bfad83d53152adb93ea00c');
  await page.locator('select').nth(1).selectOption('642d381681630b3ccefaf317');
  await page.locator('.css-ackcql').click();
  await page.locator('#react-select-7-input').fill('che');
  await page.getByText('Chennai', { exact: true }).click();
  await page.getByPlaceholder('Search by location').first().click();
  await page.getByPlaceholder('Search by location').first().fill('ann');
  await page.getByText('Anna Nagar, Chennai, Tamil Nadu, India', { exact: true }).click();
  await page.getByPlaceholder('Search by location').nth(1).click();
  await page.locator('select').nth(2).selectOption('1');
  await page.locator('#carpetAreaMininput').click();
  await page.locator('#carpetAreaMininput').fill('0');
  await page.locator('#carpetAreaMaxinput').click();
  await page.locator('#carpetAreaMaxinput').fill('13');
  await page.locator('#rentPsfMininput').click();
  await page.locator('#rentPsfMininput').fill('0');
  await page.locator('#rentPsfMaxinput').click();
  await page.locator('#rentPsfMaxinput').fill('500');
  await page.locator('div').filter({ hasText: 'Lockin period' }).nth(3).click();
  await page.getByPlaceholder('Enter lockIn period').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('select').nth(3).selectOption('63c0f7cbe611894420fbcbc6');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Got It' }).click();
});